[package]
name = "xiti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docx = "1.1.2"
jetscii = "0.5.3"
rand = "0.8.5"
